name: Python application

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Type check with mypy
        run: |
          poetry run python -m mypy .
      - name: Lint with ruff
        run: |
          poetry run ruff check .
      - name: Lint with isort
        run: |
          poetry run isort --check .
      - name: Lint with black
        run: |
          poetry run black --check .
      - name: Download sample data
        run: |
          wget https://static.webknossos.org/data/l4_sample.zip
          unzip l4_sample.zip
      - name: Run tests
        run: |
          poetry run pytest -vv tests/test_v2.py tests/test_v3.py tests/test_store.py
      - name: Run perf tests
        run: |
          TEST_SIZE=128 poetry run pytest -vv -s tests/test_perf.py
